#!/bin/sh

if [ -f ../ngram-count-gt/swbd.3bo.gz ]; then
	gz=.gz
else
	gz=
fi

ngram -debug 1 \
	-lm ../ngram-count-gt/swbd.3bo$gz \
	-seed 12345 \
	-gen 5

ngram -debug 1 \
	-lm ../ngram-count-gt/swbd.3bo$gz \
	-seed 12345 \
	-gen-prefixes prefixes | \
paste prefixes /dev/stdin
