#!/bin/sh

if [ -f spine2000+2001-gridlabel+spell.4bo.gz ]; then
	gz=.gz
else
	gz=
fi

ngram -debug 1 \
	-ppl devtest.text \
	-order 4 \
	-lm spine2000+2001-gridlabel+spell.4bo$gz \
	-classes newlabels+spell.classes 
