.\" $Id: TEMPLATE.3,v 1.5 2019/09/09 22:35:37 stolcke Exp $
.TH XXX 3 "$Date: 2019/09/09 22:35:37 $" SRILM
.SH NAME
XXX \- XXX
.SH SYNOPSIS
.nf
.B #include <XXX.h>
.fi
.SH DESCRIPTION
.SH TYPES
.SH CONSTANTS
.SH FUNCTIONS
.SH "SEE ALSO"
.SH BUGS
.SH AUTHOR
Andreas Stolcke <stolcke@icsi.berkeley.edu>
.br
Copyright (c) 1999 SRI International
