.\" $Id: TEMPLATE.1,v 1.5 2019/09/09 22:35:37 stolcke Exp $
.TH XXX 1 "$Date: 2019/09/09 22:35:37 $" "SRILM Tools"
.SH NAME
XXX \- XXX
.SH SYNOPSIS
.nf
.B XXX
.fi
.SH DESCRIPTION
.SH OPTIONS
.SH "SEE ALSO"
.SH BUGS
.SH AUTHOR
Andreas Stolcke <stolcke@icsi.berkeley.edu>
.br
Copyright (c) 1999 SRI International
